-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Category"
(
    "Category" character(250) COLLATE pg_catalog."default" NOT NULL,
    "CategoryID" smallint NOT NULL,
    CONSTRAINT "Category_pkey" PRIMARY KEY ("CategoryID")
);

CREATE TABLE IF NOT EXISTS public."Choices"
(
    "Choice_ID" smallint NOT NULL,
    "Choice" text COLLATE pg_catalog."default" NOT NULL,
    "Question_ID" smallint NOT NULL,
    CONSTRAINT "Choices_pkey" PRIMARY KEY ("Choice_ID")
);

CREATE TABLE IF NOT EXISTS public."PatientInfo"
(
    "PatientName" character(100) COLLATE pg_catalog."default" NOT NULL,
    "PhoneNumber" bigint NOT NULL,
    "Email" character(250) COLLATE pg_catalog."default" NOT NULL,
    "PatientID" smallint NOT NULL,
    CONSTRAINT "PatientInfo_pkey" PRIMARY KEY ("PatientID")
);

CREATE TABLE IF NOT EXISTS public."QuestionBank"
(
    "QuestionID" smallint NOT NULL,
    "QuestionDesc" text COLLATE pg_catalog."default" NOT NULL,
    "CatagoryID" smallint NOT NULL,
    CONSTRAINT "QuestionBank_pkey" PRIMARY KEY ("QuestionID")
);

CREATE TABLE IF NOT EXISTS public."QuestionaireResponse"
(
    "ResponseID" smallint NOT NULL,
    "UserResponse" text COLLATE pg_catalog."default" NOT NULL,
    "QuestionID" smallint NOT NULL,
    "PatientID" smallint NOT NULL,
    "DateTaken" date NOT NULL DEFAULT now(),
    CONSTRAINT "QuestionaireResponse_pkey" PRIMARY KEY ("ResponseID")
);

ALTER TABLE IF EXISTS public."Choices"
    ADD CONSTRAINT "Question_BankFK" FOREIGN KEY ("Question_ID")
    REFERENCES public."QuestionBank" ("QuestionID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."QuestionBank"
    ADD CONSTRAINT "Catagory_FK_QuestionBank" FOREIGN KEY ("CatagoryID")
    REFERENCES public."Category" ("CategoryID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."QuestionaireResponse"
    ADD CONSTRAINT "patient_FK" FOREIGN KEY ("PatientID")
    REFERENCES public."PatientInfo" ("PatientID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."QuestionaireResponse"
    ADD CONSTRAINT "questionbank_FK" FOREIGN KEY ("QuestionID")
    REFERENCES public."QuestionBank" ("QuestionID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;